name: on-release-event

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          export NODE_ENV=dev
          npm ci
          npm run lerna-ci
      - name: Run lint
        run: npm run lerna-lint
      - name: Run tests
        run: npm run lerna-test
      - name: Collate Coverage Reports
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          for d in ./packages/*/ ; do
           mkdir -p coverage
           if [[ ! -f coverage/lcov.info ]]
           then
               continue
           fi
           filename="$d""coverage/lcov.info"
           targetSource="SF:""$d""src"
           sed "s|SF:src|$targetSource|g" $filename >> coverage/lcov.info
          done
      - name: Report Coverage
        #Dependabot user will only have read-only perms, so don't try to report coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info

      - name: Publish
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          lerna publish from-package --no-commit-hooks --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}